server {
    listen 80;

    # Backend API routes → forward to Spring Boot
    location /auth/ {
        proxy_pass http://backend:8080/auth/;
    }
    
     location /admin/ {
        proxy_pass http://backend:8080/admin/;
    }


    location /class/ {
        proxy_pass http://backend:8080/class/;
    }


    location /posts/ {
        proxy_pass http://backend:8080/posts/;
    }

    location /workstations/ {
        proxy_pass http://backend:8080/workstations/;
    }

    location /class-repository/ {
        proxy_pass http://backend:8080/class-repository/;
    }

    # React app → must be LAST
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}