server {
    listen 80;

        # 🔥 COMMON PROXY SETTINGS (apply everywhere)
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    # 🔥 MOST IMPORTANT (JWT fix)
    proxy_set_header Authorization $http_authorization;

    # Backend API routes → forward to Spring Boot
    location /auth/ {
        proxy_pass http://backend:8080/auth/;
    }

     location /api/admin/ {
        proxy_pass http://backend:8080/api/admin/;
    }

    location /class/ {
        proxy_pass http://backend:8080/class/;
    }

    location /posts/ {
        proxy_pass http://backend:8080/posts/;
    }

    location /workstations/ {
        proxy_pass http://backend:8080/workstations/;
    }

    location /class-repository/ {
        proxy_pass http://backend:8080/class-repository/;
    }

    # React app → must be LAST
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}